'use client';
import {useEffect,useMemo,useState} from 'react'; import Link from 'next/link'; import {CheckCircle2,Clock3,Plus,Search,School,Trash2} from 'lucide-react'; import {createClient} from '@/lib/supabase'; import AppNav from '@/components/AppNav';
import SearchableSelect from '@/components/SearchableSelect';
export default function Tasks(){const s=createClient();const[rows,setRows]=useState<any[]>([]),[title,setTitle]=useState(''),[due,setDue]=useState(''),[priority,setPriority]=useState('MEDIUM'),[schoolId,setSchoolId]=useState(''),[schools,setSchools]=useState<any[]>([]),[search,setSearch]=useState(''),[showDone,setShowDone]=useState(false),[error,setError]=useState('');
const load=async()=>{const[r,sc]=await Promise.all([s.from('tasks').select('*,schools(id,name)').order('completed').order('due_at',{ascending:true,nullsFirst:false}),s.from('schools').select('id,name').eq('status','ACTIVE').order('name')]);setRows(r.data||[]);setSchools(sc.data||[]);if(r.error)setError(r.error.message)};useEffect(()=>{load()},[]);
const add=async()=>{if(!title.trim()){setError('Task title is required');return}const{data:{user}}=await s.auth.getUser();const r=await s.from('tasks').insert({title:title.trim(),due_at:due?new Date(due).toISOString():null,priority,school_id:schoolId||null,created_by:user?.id});if(r.error){setError(r.error.message);return}setTitle('');setDue('');setSchoolId('');setError('');load()};
const toggle=async(id:string,v:boolean)=>{const r=await s.from('tasks').update({completed:v}).eq('id',id);if(r.error)setError(r.error.message);else load()};
const remove=async(id:string)=>{if(!confirm('Delete this task?'))return;const r=await s.from('tasks').delete().eq('id',id);if(r.error)setError(r.error.message);else load()};
const visible=useMemo(()=>rows.filter(r=>(showDone||!r.completed)&&[r.title,r.schools?.name].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase())),[rows,showDone,search]);
return <div className="min-h-screen flex bg-slate-50"><AppNav/><main className="flex-1 min-w-0 p-4 md:p-8 space-y-5 max-w-[1200px] mx-auto w-full"><header><h1 className="text-2xl font-bold">Tasks</h1><p className="text-sm text-slate-500 mt-1">Keep field work and office work moving.</p></header>{error&&<div className="rounded-xl bg-red-50 text-red-700 p-3 text-sm">{error}</div>}
<section className="card p-4 grid gap-3"><div className="grid md:grid-cols-2 gap-3"><input className="border rounded-xl p-3" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Task title"/><input className="border rounded-xl p-3" type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></div><div className="grid md:grid-cols-2 gap-3"><SearchableSelect value={schoolId} onChange={setSchoolId} options={[{value:'',label:'No school linked'},...schools.map(x=>({value:x.id,label:x.name}))]} placeholder="Search school (optional)…" searchPlaceholder="Search schools…" /><select className="border rounded-xl p-3" value={priority} onChange={e=>setPriority(e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></div><button className="rounded-xl bg-slate-900 text-white p-3 font-semibold inline-flex items-center justify-center gap-2" onClick={add}><Plus size={17}/>Add task</button></section>
<section className="card p-4"><div className="flex flex-col sm:flex-row gap-3 justify-between"><label className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input className="w-full border rounded-xl p-3 pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks or schools"/></label><label className="flex items-center gap-2 text-sm px-3"><input type="checkbox" checked={showDone} onChange={e=>setShowDone(e.target.checked)}/>Show completed</label></div></section>
<div className="grid gap-3">{visible.map(r=><article className={'card p-4 '+(r.completed?'opacity-60':'')} key={r.id}><div className="flex gap-3 items-start"><button onClick={()=>toggle(r.id,!r.completed)} aria-label={r.completed?'Reopen task':'Complete task'} className="mt-1 text-emerald-600">{r.completed?<CheckCircle2/>:<span className="block h-5 w-5 rounded-full border-2 border-slate-300"/>}</button><div className="min-w-0 flex-1"><b className="block">{r.title}</b>{r.schools?.id&&<Link href={'/schools/'+r.schools.id} className="text-sm text-emerald-700 inline-flex items-center gap-1 mt-1"><School size={14}/>{r.schools.name}</Link>}<div className="text-xs text-slate-500 mt-2 flex flex-wrap gap-2">{r.due_at&&<span><Clock3 size={12} className="inline mr-1"/>{new Date(r.due_at).toLocaleString()}</span>}<span>{r.priority}</span></div></div><button onClick={()=>remove(r.id)} aria-label="Delete task" className="text-slate-400 hover:text-red-600"><Trash2 size={17}/></button></div></article>)}{!visible.length&&<div className="empty-panel">No matching tasks.</div>}</div></main></div>}