'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { CheckCircle2, LocateFixed, MapPin, Play, Square } from 'lucide-react';
import AppNav from '@/components/AppNav';
import { createClient } from '@/lib/supabase';

export default function VisitsPage(){
 const client=createClient();const [schools,setSchools]=useState<any[]>([]),[visits,setVisits]=useState<any[]>([]),[schoolId,setSchoolId]=useState(''),[active,setActive]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);const [s,v]=await Promise.all([client.from('schools').select('id,name').eq('status','ACTIVE').order('name'),client.from('school_visits').select('*,schools(name)').order('started_at',{ascending:false}).limit(50)]);if(s.error||v.error)setError((s.error||v.error)?.message||'Unable to load visits');setSchools(s.data||[]);setVisits(v.data||[]);setActive((v.data||[]).find((x:any)=>!x.ended_at)||null);setLoading(false)};useEffect(()=>{load()},[]);
 const start=()=>{if(!schoolId){setError('Choose a school first');return}navigator.geolocation?.getCurrentPosition(async p=>{const r=await client.from('school_visits').insert({school_id:schoolId,started_at:new Date().toISOString(),latitude:p.coords.latitude,longitude:p.coords.longitude,purpose:'GENERAL'}).select().single();if(r.error)setError(r.error.message);else load()},e=>setError(e.message),{enableHighAccuracy:true})};
 const end=async()=>{if(!active)return;const r=await client.from('school_visits').update({ended_at:new Date().toISOString()}).eq('id',active.id);if(r.error)setError(r.error.message);else load()};
 return <div className="min-h-screen flex bg-slate-50"><AppNav/><main className="flex-1 p-4 md:p-8"><div className="max-w-6xl mx-auto"><header className="mb-6"><p className="text-sm text-slate-500">Phase 2 · Field operations</p><h1 className="text-3xl font-bold">Visits</h1></header>{error&&<p className="mb-4 rounded-xl bg-red-50 text-red-700 p-3 text-sm">{error}</p>}
 <section className="card p-5 mb-5"><div className="flex flex-col md:flex-row gap-3"><select value={schoolId} onChange={e=>setSchoolId(e.target.value)} className="flex-1 rounded-xl border px-3 py-3"><option value="">Select school for a visit</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>{active?<button onClick={end} className="rounded-xl bg-amber-600 text-white px-5 py-3 font-semibold flex items-center justify-center gap-2"><Square size={17}/>End active visit</button>:<button onClick={start} className="rounded-xl bg-emerald-600 text-white px-5 py-3 font-semibold flex items-center justify-center gap-2"><Play size={17}/>Start GPS visit</button>}</div><p className="text-xs text-slate-500 mt-3 flex gap-1 items-center"><LocateFixed size={13}/>GPS is captured when the visit starts.</p></section>
 <section className="card p-5"><h2 className="font-bold mb-4">Recent visits</h2>{loading?<p>Loading…</p>:visits.length===0?<div className="py-12 text-center text-slate-500"><CheckCircle2 className="mx-auto mb-3"/><p>No visits yet.</p></div>:<div className="divide-y">{visits.map(v=><div key={v.id} className="py-4 flex justify-between gap-4"><div><Link href={'/schools/'+v.school_id} className="font-semibold hover:text-emerald-700">{v.schools?.name||'School'}</Link><p className="text-sm text-slate-500">{new Date(v.started_at).toLocaleString()} · {v.purpose}</p>{v.latitude&&<p className="text-xs text-slate-400 mt-1"><MapPin size={12} className="inline"/> {Number(v.latitude).toFixed(5)}, {Number(v.longitude).toFixed(5)}</p>}</div><span className={'text-xs rounded-full px-2.5 py-1 h-fit '+(v.ended_at?'bg-slate-100 text-slate-600':'bg-emerald-50 text-emerald-700')}>{v.ended_at?'Completed':'Active'}</span></div>)}</div>}</section>
 </div></main></div>;
}
