'use client';
import {useEffect,useMemo,useState} from 'react'; import Link from 'next/link'; import {AlertCircle,BellRing,CalendarClock,CheckCircle2,Clock3,Plus,Search,School,TimerReset,Trash2} from 'lucide-react'; import {createClient} from '@/lib/supabase'; import AppNav from '@/components/AppNav';
export default function Reminders(){const s=createClient();const[rows,setRows]=useState<any[]>([]),[title,setTitle]=useState(''),[due,setDue]=useState(''),[priority,setPriority]=useState('MEDIUM'),[desc,setDesc]=useState(''),[schoolId,setSchoolId]=useState(''),[schools,setSchools]=useState<any[]>([]),[search,setSearch]=useState(''),[showDone,setShowDone]=useState(false),[error,setError]=useState('');
const load=async()=>{const[r,sc]=await Promise.all([s.from('reminders').select('*,schools(id,name)').order('completed').order('due_at',{ascending:true}),s.from('schools').select('id,name').eq('status','ACTIVE').order('name')]);setRows(r.data||[]);setSchools(sc.data||[]);if(r.error)setError(r.error.message)};useEffect(()=>{load()},[]);
const add=async()=>{if(!title.trim()||!due){setError('Title and due date are required');return}const{data:{user}}=await s.auth.getUser();const r=await s.from('reminders').insert({title:title.trim(),description:desc.trim()||null,due_at:new Date(due).toISOString(),priority,school_id:schoolId||null,created_by:user?.id});if(r.error){setError(r.error.message);return}setTitle('');setDue('');setDesc('');setSchoolId('');setError('');load()};
const toggle=async(id:string,v:boolean)=>{const r=await s.from('reminders').update({completed:v}).eq('id',id);if(r.error)setError(r.error.message);else load()};
const remove=async(id:string)=>{if(!confirm('Delete this reminder?'))return;const r=await s.from('reminders').delete().eq('id',id);if(r.error)setError(r.error.message);else load()};
const dueState=(value:string)=>{const d=new Date(value),now=new Date();const start=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime();const time=d.getTime();return time<start?'overdue':time<start+86400000?'today':'upcoming'};
const [filter,setFilter]=useState<'all'|'overdue'|'today'|'upcoming'|'completed'>('all');
const active=rows.filter(r=>!r.completed);const counts={all:active.length,overdue:active.filter(r=>dueState(r.due_at)==='overdue').length,today:active.filter(r=>dueState(r.due_at)==='today').length,upcoming:active.filter(r=>dueState(r.due_at)==='upcoming').length,completed:rows.filter(r=>r.completed).length};
const visible=useMemo(()=>rows.filter(r=>{const match=[r.title,r.description,r.schools?.name].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase());const status=filter==='all'?!r.completed:filter==='completed'?r.completed:!r.completed&&dueState(r.due_at)===filter;return match&&status}),[rows,search,filter]);
const snooze=async(id:string,dueAt:string)=>{const next=new Date(dueAt);next.setDate(next.getDate()+1);const r=await s.from('reminders').update({due_at:next.toISOString()}).eq('id',id);if(r.error)setError(r.error.message);else{setError('');await load()}};
return <div className="min-h-screen flex bg-slate-50"><AppNav/><main className="flex-1 min-w-0 p-4 md:p-8 space-y-5 max-w-[1200px] mx-auto w-full"><header><h1 className="text-2xl font-bold">Reminders</h1><p className="text-xs text-emerald-700 font-semibold mt-1">PHASE 33 · REMINDER TRIAGE</p><p className="text-sm text-slate-500 mt-1">Never miss a collection, visit, delivery or follow-up.</p></header>{error&&<div className="rounded-xl bg-red-50 text-red-700 p-3 text-sm">{error}</div>}
<section className="card p-4 grid gap-3"><div className="grid md:grid-cols-2 gap-3"><input className="border rounded-xl p-3" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Reminder title"/><input className="border rounded-xl p-3" type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></div><div className="grid md:grid-cols-2 gap-3"><select className="border rounded-xl p-3" value={schoolId} onChange={e=>setSchoolId(e.target.value)}><option value="">No school linked</option>{schools.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="border rounded-xl p-3" value={priority} onChange={e=>setPriority(e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></div><input className="border rounded-xl p-3" value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Description"/><button className="rounded-xl bg-slate-900 text-white p-3 font-semibold inline-flex items-center justify-center gap-2" onClick={add}><Plus size={17}/>Add reminder</button></section>
<section className="grid grid-cols-2 md:grid-cols-5 gap-3">{([{key:'all',label:'Open reminders',icon:BellRing},{key:'overdue',label:'Overdue',icon:AlertCircle},{key:'today',label:'Due today',icon:CalendarClock},{key:'upcoming',label:'Upcoming',icon:Clock3},{key:'completed',label:'Completed',icon:CheckCircle2}] as const).map(x=><button key={x.key} onClick={()=>{setFilter(x.key);setShowDone(x.key==='completed')}} className={'card p-4 text-left transition-all hover:-translate-y-0.5 '+(filter===x.key?'ring-2 ring-emerald-400':'')}><x.icon size={18} className="text-emerald-700"/><b className="block text-2xl mt-2">{counts[x.key]}</b><span className="text-xs text-slate-500">{x.label}</span></button>)}</section>
<section className="card p-4"><div className="flex flex-col sm:flex-row gap-3 justify-between"><label className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input className="w-full border rounded-xl p-3 pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search reminders or schools"/></label><label className="flex items-center gap-2 text-sm px-3"><input type="checkbox" checked={showDone} onChange={e=>setShowDone(e.target.checked)}/>Show completed</label></div></section>
<div className="grid gap-3">{visible.map(r=><article className={'card p-4 '+(r.completed?'opacity-60':'')} key={r.id}><div className="flex gap-3 items-start"><button onClick={()=>toggle(r.id,!r.completed)} aria-label={r.completed?'Reopen reminder':'Complete reminder'} className="mt-1 text-amber-600">{r.completed?<CheckCircle2/>:<span className="block h-5 w-5 rounded-full border-2 border-slate-300"/>}</button><div className="min-w-0 flex-1"><b className="block">{r.title}</b>{r.schools?.id&&<Link href={'/schools/'+r.schools.id} className="text-sm text-amber-700 inline-flex items-center gap-1 mt-1"><School size={14}/>{r.schools.name}</Link>}<p className="text-sm text-slate-600 mt-1">{r.description||'No description'}</p><div className="text-xs text-slate-500 mt-2 flex flex-wrap gap-2"><span><Clock3 size={12} className="inline mr-1"/>{new Date(r.due_at).toLocaleString()}</span><span>{r.priority}</span></div></div><div className="flex items-center gap-1">{!r.completed&&<button onClick={()=>void snooze(r.id,r.due_at)} aria-label="Snooze reminder for one day" title="Snooze 1 day" className="rounded-lg border p-2 text-slate-500 hover:text-amber-700"><TimerReset size={17}/></button>}<button onClick={()=>remove(r.id)} aria-label="Delete reminder" className="text-slate-400 hover:text-red-600"><Trash2 size={17}/></button></div></div></article>)}{!visible.length&&<div className="empty-panel">No matching reminders.</div>}</div></main></div>}