'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, ChevronDown, ChevronUp, Filter, RefreshCw, Search } from 'lucide-react';
import AppNav from '@/components/AppNav';
import { createClient } from '@/lib/supabase';

type Log={id:number;actor_id:string|null;entity_type:string;entity_id:string|null;action:string;old_data:Record<string,unknown>|null;new_data:Record<string,unknown>|null;created_at:string};
const actions=['ALL','INSERT','UPDATE','DELETE'];
const entityLabels:Record<string,string>={orders:'Orders',order_items:'Order items',schools:'Schools',school_visits:'School visits',products:'Products',payments:'Payments',deliveries:'Deliveries',purchases:'Purchases',inventory_transactions:'Inventory',suppliers:'Suppliers',tasks:'Tasks',reminders:'Reminders'};
function prettyEntity(v:string){return entityLabels[v]||v.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())}
function formatAction(action:string){return action==='INSERT'?'Created':action==='UPDATE'?'Updated':'Deleted'}
function diff(oldData:Record<string,unknown>|null,newData:Record<string,unknown>|null){if(!oldData&&!newData)return [];const keys=Array.from(new Set([...Object.keys(oldData||{}),...Object.keys(newData||{})]));return keys.filter(k=>JSON.stringify(oldData?.[k])!==JSON.stringify(newData?.[k])).slice(0,12).map(k=>({key:k,oldValue:oldData?.[k],newValue:newData?.[k]}))}
function display(v:unknown){if(v===null||v===undefined)return '—';if(typeof v==='object')return JSON.stringify(v);return String(v)}

export default function Timeline(){
 const supabase=createClient();const[rows,setRows]=useState<Log[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[search,setSearch]=useState('');const[action,setAction]=useState('ALL');const[entity,setEntity]=useState('ALL');const[expanded,setExpanded]=useState<number|null>(null);
 const load=async()=>{setLoading(true);setError('');const r=await supabase.from('activity_logs').select('id,actor_id,entity_type,entity_id,action,old_data,new_data,created_at').order('created_at',{ascending:false}).limit(500);if(r.error)setError(r.error.message);else setRows((r.data||[]) as Log[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const entities=useMemo(()=>Array.from(new Set(rows.map(r=>r.entity_type))).sort(),[rows]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>{if(action!=='ALL'&&r.action!==action)return false;if(entity!=='ALL'&&r.entity_type!==entity)return false;if(!q)return true;return[r.entity_type,r.action,r.entity_id,r.actor_id,JSON.stringify(r.old_data),JSON.stringify(r.new_data)].filter(Boolean).join(' ').toLowerCase().includes(q)})},[rows,search,action,entity]);
 return <div className="min-h-screen flex bg-slate-50"><AppNav/><main className="flex-1 min-w-0 p-4 md:p-8"><div className="max-w-5xl mx-auto">
  <header className="mb-6 flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="text-sm font-semibold text-emerald-600 flex items-center gap-2"><Activity size={15}/>Audit trail</p><h1 className="text-3xl font-bold">Activity Timeline</h1><p className="text-sm text-slate-500 mt-1">Review recent record changes and inspect what changed.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50"><RefreshCw size={16} className={loading?'animate-spin':''}/>Refresh</button></header>
  <section className="card p-4 mb-5"><div className="flex items-center gap-2 mb-3 text-sm font-semibold"><Filter size={16}/>Filters</div><div className="grid gap-2 md:grid-cols-[1fr_170px_190px]"><label className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search action, entity, ID or changed data…" className="w-full rounded-xl border px-9 py-2.5 text-sm"/></label><select value={action} onChange={e=>setAction(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm">{actions.map(x=><option key={x} value={x}>{x==='ALL'?'All actions':formatAction(x)}</option>)}</select><select value={entity} onChange={e=>setEntity(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option value="ALL">All entities</option>{entities.map(x=><option key={x} value={x}>{prettyEntity(x)}</option>)}</select></div><p className="mt-3 text-xs text-slate-500">{filtered.length} of {rows.length} events</p></section>
  {error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  {loading?<div className="card p-8 text-center text-slate-500">Loading activity…</div>:!filtered.length?<div className="card p-10 text-center text-slate-500">No activity matches the current filters.</div>:<div className="space-y-3">{filtered.map(row=>{const changes=diff(row.old_data,row.new_data);const isOpen=expanded===row.id;return <article key={row.id} className="card overflow-hidden"><button type="button" onClick={()=>setExpanded(isOpen?null:row.id)} className="w-full p-4 text-left hover:bg-slate-50"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><Activity size={18}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b>{formatAction(row.action)} {prettyEntity(row.entity_type)}</b><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[11px]">{row.action}</span></div><p className="mt-1 text-xs text-slate-500">{row.entity_id?'ID '+row.entity_id.slice(0,8)+' · ':''}{new Date(row.created_at).toLocaleString('en-IN')} {row.actor_id?' · Actor '+row.actor_id.slice(0,8):''}</p>{!isOpen&&changes.length>0&&<p className="mt-2 text-sm text-slate-600">{changes.slice(0,3).map(x=>x.key).join(' · ')}{changes.length>3?' · …':''}</p>}</div>{isOpen?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</div></button>{isOpen&&<div className="border-t bg-slate-50/70 p-4">{changes.length?<div className="space-y-2">{changes.map(x=><div key={x.key} className="grid gap-1 rounded-xl border bg-white p-3 sm:grid-cols-[170px_1fr_1fr]"><b className="text-sm">{x.key}</b><div className="text-xs text-red-700"><span className="font-semibold">Before:</span> {display(x.oldValue)}</div><div className="text-xs text-emerald-700"><span className="font-semibold">After:</span> {display(x.newValue)}</div></div>)}</div>:<p className="text-sm text-slate-500">No field-level differences recorded for this event.</p>}</div>}</article>})}</div>}
 </div></main></div>;
}