'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import AppNav from '@/components/AppNav';
import { createClient } from '@/lib/supabase';
import { CalendarClock, CheckCircle2, Download, RefreshCw, Search, Truck, AlertTriangle, ClipboardList } from 'lucide-react';

type Order={id:string;order_number:number;school_id:string;order_date:string;expected_delivery_date:string|null;status:string;payment_status:string;total:number|string;school?:{name:string}|{name:string}[]|null};
type Delivery={id:string;order_id:string;school_id:string;scheduled_date:string|null;scheduled_time:string|null;status:string;delivered_at:string|null;delivery_notes:string|null;school?:{name:string}|{name:string}[]|null;order?:{order_number:number;total:number;status:string}|{order_number:number;total:number;status:string}[]|null};
const nameOf=(v:Order['school']|Delivery['school'])=>Array.isArray(v)?v[0]?.name||'School':v?.name||'School';
const dateText=(v:string|null)=>{if(!v)return 'Not scheduled';const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})};
const money=(v:number|string)=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const activeStatuses=['NEW','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','PARTIALLY_DELIVERED'];
export default function OrderFulfillmentMonitor(){
 const db=useMemo(()=>createClient(),[]);
 const [orders,setOrders]=useState<Order[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('ACTIVE'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');const [o,d]=await Promise.all([db.from('orders').select('id,order_number,school_id,order_date,expected_delivery_date,status,payment_status,total,school:schools(name)').order('created_at',{ascending:false}).limit(1000),db.from('deliveries').select('id,order_id,school_id,scheduled_date,scheduled_time,status,delivered_at,delivery_notes,school:schools(name),order:orders(order_number,total,status)').order('scheduled_date',{ascending:true,nullsFirst:false}).limit(1000)]);if(o.error||d.error)setError(o.error?.message||d.error?.message||'Unable to load fulfilment records.');setOrders((o.data||[]) as unknown as Order[]);setDeliveries((d.data||[]) as unknown as Delivery[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const deliveryByOrder=useMemo(()=>{const m=new Map<string,Delivery[]>();for(const d of deliveries){const a=m.get(d.order_id)||[];a.push(d);m.set(d.order_id,a)}return m},[deliveries]);
 const rows=useMemo(()=>orders.filter(o=>{const q=query.trim().toLowerCase();const ds=deliveryByOrder.get(o.id)||[];const hay=[o.order_number,nameOf(o.school),o.status,o.payment_status,...ds.map(d=>d.status),...ds.map(d=>d.delivery_notes||'')].join(' ').toLowerCase();const current=ds.some(d=>d.status==='DELIVERED')||o.status==='DELIVERED'?'DELIVERED':ds.some(d=>['OUT_FOR_DELIVERY','PREPARING'].includes(d.status))||['OUT_FOR_DELIVERY','PREPARING'].includes(o.status)?'IN_PROGRESS':o.status==='CANCELLED'?'CANCELLED':activeStatuses.includes(o.status)?'ACTIVE':'OTHER';return(!q||hay.includes(q))&&(status==='ALL'||status===current)&&(!from||o.order_date>=from)&&(!to||o.order_date<=to)}),[orders,deliveryByOrder,query,status,from,to]);
 const stats=useMemo(()=>({active:orders.filter(o=>activeStatuses.includes(o.status)).length,delivered:orders.filter(o=>o.status==='DELIVERED').length,scheduled:deliveries.filter(d=>d.status!=='DELIVERED'&&!!d.scheduled_date).length,late:orders.filter(o=>activeStatuses.includes(o.status)&&o.expected_delivery_date&&o.expected_delivery_date<new Date().toISOString().slice(0,10)).length}),[orders,deliveries]);
 const exportCsv=()=>{const data=[['Order','School','Order date','Expected delivery','Order status','Payment status','Order total','Delivery count','Delivery statuses','Next scheduled date','Delivery notes'],...rows.map(o=>{const ds=deliveryByOrder.get(o.id)||[];const next=ds.filter(d=>d.status!=='DELIVERED'&&d.scheduled_date).sort((a,b)=>(a.scheduled_date||'').localeCompare(b.scheduled_date||''))[0];return[o.order_number,nameOf(o.school),o.order_date,o.expected_delivery_date||'',o.status,o.payment_status,o.total,ds.length,ds.map(d=>d.status).join('; '),next?.scheduled_date||'',ds.map(d=>d.delivery_notes||'').filter(Boolean).join('; ')]})];const csv=data.map(r=>r.map(v=>{const s=String(v??'');return/[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}).join(',')).join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='guru-kalyanam-order-fulfillment.csv';a.click();URL.revokeObjectURL(url)};
 return <div className="min-h-screen flex bg-slate-50"><AppNav/><main className="flex-1 min-w-0 p-4 md:p-8"><div className="max-w-7xl mx-auto space-y-5">
 <header className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-3"><div><p className="text-sm font-semibold text-teal-700 flex items-center gap-2"><Truck size={16}/> Phase 50 · Operations</p><h1 className="text-3xl font-bold">Order Fulfilment Monitor</h1><p className="text-sm text-slate-500 mt-1">See open orders, delivery schedules, overdue commitments, and delivery progress in one place.</p></div><div className="flex gap-2"><button onClick={exportCsv} disabled={!rows.length} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50"><Download size={16}/>Export CSV</button><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50"><RefreshCw size={16} className={loading?'animate-spin':''}/>Refresh</button></div></header>
 {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <section className="grid grid-cols-2 xl:grid-cols-4 gap-3">{[['Open orders',stats.active,ClipboardList,'bg-blue-100 text-blue-700'],['Delivered orders',stats.delivered,CheckCircle2,'bg-emerald-100 text-emerald-700'],['Scheduled deliveries',stats.scheduled,CalendarClock,'bg-violet-100 text-violet-700'],['Overdue commitments',stats.late,AlertTriangle,'bg-amber-100 text-amber-700']].map(([label,value,Icon,tone]:any)=><div className="card p-4" key={label}><span className={`grid h-9 w-9 place-items-center rounded-lg ${tone}`}><Icon size={17}/></span><p className="text-xs text-slate-500 mt-3">{label}</p><b className="text-2xl">{value}</b></div>)}</section>
 <section className="card p-4 space-y-3"><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-2"><label className="relative sm:col-span-2 xl:col-span-1"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input aria-label="Search orders and schools" className="w-full border rounded-xl px-9 py-2.5 text-sm" placeholder="Search school, order, status…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Fulfilment status" className="border rounded-xl px-3 py-2.5 text-sm bg-white" value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">Open orders</option><option value="IN_PROGRESS">In progress</option><option value="DELIVERED">Delivered</option><option value="CANCELLED">Cancelled</option><option value="OTHER">Other statuses</option><option value="ALL">All orders</option></select><input aria-label="Order date from" type="date" className="border rounded-xl px-3 py-2.5 text-sm" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="Order date to" type="date" min={from||undefined} className="border rounded-xl px-3 py-2.5 text-sm" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="flex items-center justify-between text-xs text-slate-500"><span>{loading?'Loading orders…':`Showing ${rows.length} of ${orders.length} orders`}</span><button className="underline" onClick={()=>{setQuery('');setStatus('ACTIVE');setFrom('');setTo('')}}>Clear filters</button></div>
 <div className="space-y-3">{rows.map(o=>{const ds=deliveryByOrder.get(o.id)||[];const next=ds.filter(d=>d.status!=='DELIVERED'&&d.scheduled_date).sort((a,b)=>(a.scheduled_date||'').localeCompare(b.scheduled_date||''))[0];const late=activeStatuses.includes(o.status)&&!!o.expected_delivery_date&&o.expected_delivery_date<new Date().toISOString().slice(0,10);return <article key={o.id} className="rounded-xl border bg-white p-4 space-y-3"><div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2"><div><p className="font-bold">Order #{o.order_number}</p><p className="text-sm text-slate-600">{nameOf(o.school)}</p><p className="text-xs text-slate-500 mt-1">Placed {dateText(o.order_date)} · {money(o.total)}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{o.status.replaceAll('_',' ')}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${late?'bg-amber-100 text-amber-800':'bg-slate-100 text-slate-600'}`}>{late?'Overdue':o.payment_status.replaceAll('_',' ')}</span></div></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-sm"><div><p className="text-xs text-slate-500">Expected delivery</p><p className="font-medium">{dateText(o.expected_delivery_date)}</p></div><div><p className="text-xs text-slate-500">Delivery records</p><p className="font-medium">{ds.length} · {ds.map(d=>d.status.replaceAll('_',' ')).join(', ')||'No delivery record'}</p></div><div><p className="text-xs text-slate-500">Next scheduled</p><p className="font-medium">{next?dateText(next.scheduled_date)+(next.scheduled_time?' · '+next.scheduled_time:''):'Not scheduled'}</p></div></div><div className="flex flex-wrap gap-3 text-sm"><Link className="font-semibold text-teal-700 underline" href="/orders">Open orders</Link><Link className="font-semibold text-teal-700 underline" href="/deliveries">Manage deliveries</Link>{late&&<span className="text-amber-700 text-xs self-center">Expected date has passed; verify and update the order.</span>}</div></article>})}{!loading&&rows.length===0&&<div className="py-12 text-center text-slate-500">No orders match these filters.</div>}</div>
 <p className="text-xs text-slate-500">Read-only monitor · Uses existing orders and deliveries. Dates and statuses reflect the latest records in the database.</p></section>
 </div></main></div>;
}
