'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import AppNav from '@/components/AppNav';
import { createClient } from '@/lib/supabase';

type Order={id:string;order_number:number;school_id:string;contact_id:string|null;order_date:string;expected_delivery_date:string|null;status:string;payment_status:string;subtotal:number;discount:number;tax_amount:number;total:number;paid_amount:number;notes:string|null;school?:{name:string}[]};
type Item={id:string;product_id:string|null;product_name:string;quantity:number;unit:string;unit_price:number;discount:number;tax_rate:number;line_total:number;custom_item:boolean};
type Product={id:string;name:string;unit:string;selling_price:number;tax_rate:number};
const statuses=['NEW','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','PARTIALLY_DELIVERED','CANCELLED'];
const payments=['UNPAID','PARTIAL','PAID','OVERDUE'];

export default function OrderDetailPage(){
 const {id}=useParams<{id:string}>();const router=useRouter();const supabase=createClient();
 const [order,setOrder]=useState<Order|null>(null),[items,setItems]=useState<Item[]>([]),[products,setProducts]=useState<Product[]>([]),[status,setStatus]=useState('NEW'),[payment,setPayment]=useState('UNPAID'),[expected,setExpected]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState('');
 const [newProduct,setNewProduct]=useState(''),[qty,setQty]=useState('1');
 const load=async()=>{const [o,i,p]=await Promise.all([supabase.from('orders').select('*,school:schools(name)').eq('id',id).single(),supabase.from('order_items').select('*').eq('order_id',id).order('created_at'),supabase.from('products').select('id,name,unit,selling_price,tax_rate').eq('active',true).order('name')]);if(o.error){setError(o.error.message);return;}setOrder(o.data as Order);setStatus(o.data.status);setPayment(o.data.payment_status);setExpected(o.data.expected_delivery_date||'');setNotes(o.data.notes||'');setItems((i.data||[]) as Item[]);setProducts((p.data||[]) as Product[])};
 useEffect(()=>{load()},[id]);
 const saveHeader=async(e:FormEvent)=>{e.preventDefault();const {error:e2}=await supabase.from('orders').update({status,payment_status:payment,expected_delivery_date:expected||null,notes:notes.trim()||null}).eq('id',id);if(e2)setError(e2.message);else await load()};
 const addItem=async(e:FormEvent)=>{e.preventDefault();const p=products.find(x=>x.id===newProduct);if(!p)return;const q=Number(qty);if(q<=0){setError('Quantity must be greater than zero.');return;}const {error:e2}=await supabase.from('order_items').insert({order_id:id,product_id:p.id,product_name:p.name,quantity:q,unit:p.unit,unit_price:p.selling_price,discount:0,tax_rate:p.tax_rate,line_total:q*p.selling_price*(1+p.tax_rate/100),custom_item:false});if(e2){setError(e2.message);return;}await supabase.rpc('recalculate_order_totals',{p_order_id:id});setNewProduct('');setQty('1');await load()};
 const removeItem=async(itemId:string)=>{if(!confirm('Remove this item?'))return;const {error:e2}=await supabase.from('order_items').delete().eq('id',itemId);if(e2)setError(e2.message);else{await supabase.rpc('recalculate_order_totals',{p_order_id:id});await load()}};
 const removeOrder=async()=>{if(!confirm('Delete this order and its items?'))return;const {error:e2}=await supabase.from('orders').delete().eq('id',id);if(e2)setError(e2.message);else router.push('/orders')};
 if(!order)return <div className="min-h-screen flex bg-slate-50"><AppNav/><main className="flex-1 p-6"><div className="card p-8">{error||'Loading…'}</div></main></div>;
 return <div className="min-h-screen flex bg-slate-50"><AppNav/><main className="flex-1 p-4 md:p-8"><div className="max-w-5xl mx-auto">
 <div className="flex justify-between items-start gap-3 mb-6"><div><Link href="/orders" className="text-sm text-emerald-700">← Orders</Link><h1 className="text-3xl font-bold mt-1">Order #{order.order_number}</h1><p className="text-slate-500">{order.school?.[0]?.name||'School'} · {order.order_date}</p></div><button onClick={removeOrder} className="text-red-600 border rounded-xl px-3 py-2 text-sm">Delete</button></div>
 <section className="card p-4 mb-5"><div className="grid grid-cols-2 md:grid-cols-4 gap-2">{statuses.map((s,i)=><div key={s} className={'rounded-xl p-3 text-center text-xs '+(statuses.indexOf(status)>=i&&status!=='CANCELLED'?'bg-emerald-50 text-emerald-800':'bg-slate-50 text-slate-500')}><div className="font-bold">{i+1}</div>{s.replaceAll('_',' ')}</div>)}</div></section>
 <div className="grid lg:grid-cols-[1fr_320px] gap-5"><section className="card p-4"><h2 className="font-bold mb-3">Items</h2><div className="space-y-2">{items.map(i=><div key={i.id} className="border rounded-xl p-3 flex justify-between gap-3"><div><b>{i.product_name}</b><p className="text-xs text-slate-500">{i.quantity} {i.unit} · ₹{Number(i.unit_price).toFixed(2)} · {i.tax_rate}% tax</p></div><div className="text-right"><b>₹{Number(i.line_total).toFixed(2)}</b><button onClick={()=>removeItem(i.id)} className="block text-xs text-red-600 mt-1 ml-auto">Remove</button></div></div>)}</div><form onSubmit={addItem} className="grid grid-cols-[1fr_90px_auto] gap-2 mt-4"><select className="border rounded-xl px-2 py-2" value={newProduct} onChange={e=>setNewProduct(e.target.value)}><option value="">Add product…</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="border rounded-xl px-2 py-2" type="number" min="0.01" step="0.01" value={qty} onChange={e=>setQty(e.target.value)}/><button className="bg-emerald-600 text-white rounded-xl px-3">Add</button></form></section>
 <aside><form onSubmit={saveHeader} className="card p-4 space-y-3"><h2 className="font-bold">Pipeline</h2><label className="block text-sm">Order status<select className="w-full mt-1 border rounded-xl px-3 py-2" value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="block text-sm">Payment status<select className="w-full mt-1 border rounded-xl px-3 py-2" value={payment} onChange={e=>setPayment(e.target.value)}>{payments.map(s=><option key={s}>{s}</option>)}</select></label><label className="block text-sm">Expected delivery<input className="w-full mt-1 border rounded-xl px-3 py-2" type="date" value={expected} onChange={e=>setExpected(e.target.value)}/></label><textarea className="w-full border rounded-xl px-3 py-2" placeholder="Notes" value={notes} onChange={e=>setNotes(e.target.value)}/>{error&&<p className="text-sm text-red-600">{error}</p>}<button className="w-full bg-emerald-600 text-white rounded-xl py-2 font-semibold">Save order</button></form><div className="card p-4 mt-3"><div className="text-sm text-slate-500">Subtotal</div><div>₹{Number(order.subtotal).toFixed(2)}</div><div className="text-sm text-slate-500 mt-2">Tax</div><div>₹{Number(order.tax_amount).toFixed(2)}</div><div className="text-sm text-slate-500 mt-2">Total</div><div className="text-2xl font-bold">₹{Number(order.total).toFixed(2)}</div></div></aside></div>
 </div></main></div>;
}