'use client';
import {useEffect,useMemo,useState} from 'react';
import AppNav from '@/components/AppNav';
import {createClient} from '@/lib/supabase';
import {Printer,Search,ReceiptText,RefreshCw,Share2,Download} from 'lucide-react';
type Supplier={id:string;name:string;company:string|null;address?:string|null;phone?:string|null};
type Purchase={id:string;purchase_number:number;supplier_id:string;purchase_date:string;total:number|string;status:string};
type Payment={id:string;supplier_id:string;purchase_id:string|null;payment_date:string;amount:number|string;payment_mode:string;reference_number:string|null;notes:string|null;is_advance:boolean;created_at:string;suppliers?:{name:string;company?:string|null}|{name:string;company?:string|null}[]|null;purchases?:{purchase_number:number}|{purchase_number:number}[]|null};
const money=(v:number)=>'₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const dateLabel=(v:string)=>{if(!v)return '—';const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})};
const supplierName=(p:Payment)=>Array.isArray(p.suppliers)?p.suppliers[0]?.name||'Supplier':p.suppliers?.name||'Supplier';
const purchaseNo=(p:Payment)=>Array.isArray(p.purchases)?p.purchases[0]?.purchase_number:p.purchases?.purchase_number;
export default function SupplierPaymentVouchersPage(){
 const db=useMemo(()=>createClient(),[]);const [suppliers,setSuppliers]=useState<Supplier[]>([]),[purchases,setPurchases]=useState<Purchase[]>([]),[payments,setPayments]=useState<Payment[]>([]);
 const [selected,setSelected]=useState(''),[query,setQuery]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');const [s,p,h]=await Promise.all([
  db.from('suppliers').select('id,name,company,address,phone').order('name'),
  db.from('purchases').select('id,purchase_number,supplier_id,purchase_date,total,status'),
  db.from('supplier_payments').select('id,supplier_id,purchase_id,payment_date,amount,payment_mode,reference_number,notes,is_advance,created_at,suppliers(name,company),purchases(purchase_number)').order('payment_date',{ascending:false}).order('created_at',{ascending:false}).limit(500)]);
 const e=s.error||p.error||h.error;if(e)setError(e.message);setSuppliers((s.data||[]) as Supplier[]);setPurchases((p.data||[]) as Purchase[]);setPayments((h.data||[]) as unknown as Payment[]);if(!selected&&h.data?.length)setSelected(h.data[0].id);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const supplierById=useMemo(()=>new Map(suppliers.map(s=>[s.id,s])),[suppliers]);
 const purchaseById=useMemo(()=>new Map(purchases.map(p=>[p.id,p])),[purchases]);
 const visible=useMemo(()=>payments.filter(p=>{const q=query.trim().toLowerCase();const s=supplierById.get(p.supplier_id);const po=p.purchase_id?purchaseById.get(p.purchase_id):undefined;return(!q||[s?.name,s?.company,p.reference_number,p.notes,p.payment_mode,po?String(po.purchase_number):'',p.is_advance?'advance':''].filter(Boolean).join(' ').toLowerCase().includes(q))&&(!start||p.payment_date>=start)&&(!end||p.payment_date<=end)}),[payments,query,start,end,supplierById,purchaseById]);
 const chosen=payments.find(p=>p.id===selected)||visible[0]||null;const supplier=chosen?supplierById.get(chosen.supplier_id):undefined;const purchase=chosen?.purchase_id?purchaseById.get(chosen.purchase_id):undefined;
 const exportCsv=()=>{const records=[['Voucher number','Date','Supplier','Company','Purchase order','Payment mode','Reference','Advance','Amount','Notes'],...visible.map(p=>{const s=supplierById.get(p.supplier_id);return[p.id.slice(0,8).toUpperCase(),p.payment_date,s?.name||'Supplier',s?.company||'',p.purchase_id?purchaseById.get(p.purchase_id)?.purchase_number||'':'',p.payment_mode,p.reference_number||'',p.is_advance?'Yes':'No',p.amount,p.notes||'']})];const csv=records.map(row=>row.map(v=>{const x=String(v??'');return/[",\n\r]/.test(x)?'"'+x.replace(/"/g,'""')+'"':x}).join(',')).join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='guru-kalyanam-supplier-payment-vouchers.csv';a.click();URL.revokeObjectURL(url)};
 const share=async()=>{if(!chosen)return;const textBody=['SUPPLIER PAYMENT VOUCHER','Guru Kalyanam · School Supply Ops','Voucher: '+chosen.id.slice(0,8).toUpperCase(),'Paid to: '+(supplier?.name||'Supplier'),supplier?.company?'Company: '+supplier.company:'','Date: '+dateLabel(chosen.payment_date),'Amount paid: '+money(Number(chosen.amount)),'Payment mode: '+chosen.payment_mode.replaceAll('_',' '),purchase?'Against purchase: #'+purchase.purchase_number:'',chosen.is_advance?'Type: Advance / supplier credit':'Type: Purchase payment',chosen.reference_number?'Reference: '+chosen.reference_number:'',chosen.notes?'Notes: '+chosen.notes:''].filter(Boolean).join('\n');try{if(navigator.share)await navigator.share({title:'Supplier payment voucher',text:textBody});else if(navigator.clipboard){await navigator.clipboard.writeText(textBody);window.alert('Voucher details copied. Paste them into WhatsApp.')}else window.print()}catch(e){if(e instanceof Error&&e.name!=='AbortError')setError('Could not open sharing. Use Print / Save PDF instead.')}};
 return <div className="min-h-screen flex bg-slate-50"><AppNav/><main className="flex-1 min-w-0 p-4 md:p-8"><div className="max-w-7xl mx-auto space-y-5">
 <header className="no-print"><p className="text-sm text-violet-700 font-semibold">Phase 48 · Procurement finance</p><h1 className="text-2xl md:text-3xl font-extrabold">Supplier payment vouchers</h1><p className="text-sm text-slate-500 mt-1">Find a recorded supplier payment and print, save or share its voucher. This screen never creates or changes payments.</p></header>
 <section className="grid grid-cols-2 md:grid-cols-3 gap-3 no-print"><div className="card p-4"><p className="text-xs text-slate-500">Loaded payments</p><p className="text-2xl font-bold">{payments.length}</p></div><div className="card p-4"><p className="text-xs text-slate-500">Paid in loaded history</p><p className="text-xl font-bold text-violet-700">{money(payments.reduce((n,p)=>n+Number(p.amount||0),0))}</p></div><div className="card p-4 col-span-2 md:col-span-1"><p className="text-xs text-slate-500">Voucher number</p><p className="text-xl font-bold">{chosen?chosen.id.slice(0,8).toUpperCase():'—'}</p></div></section>
 <div className="grid lg:grid-cols-[minmax(280px,.9fr)_minmax(0,1.1fr)] gap-5 items-start">
 <section className="card p-4 space-y-3 no-print"><div className="flex justify-between items-center gap-2"><h2 className="font-bold">Recorded supplier payments</h2><button onClick={()=>void load()} disabled={loading} className="border rounded-xl px-3 py-2 text-sm inline-flex items-center gap-2 disabled:opacity-50"><RefreshCw size={15}/>Refresh</button></div>
 <label className="relative block"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input className="w-full border rounded-xl pl-9 pr-3 py-2" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search supplier, PO or reference"/></label>
 <div className="grid grid-cols-2 gap-2"><label className="text-xs text-slate-500">From<input type="date" className="block w-full border rounded-xl px-2 py-2 mt-1 text-sm" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-xs text-slate-500">To<input type="date" className="block w-full border rounded-xl px-2 py-2 mt-1 text-sm" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>
 {error&&<p role="alert" className="text-sm text-red-600 break-words">{error}</p>}{loading?<p className="py-8 text-center text-slate-500">Loading supplier payments…</p>:visible.length===0?<p className="py-8 text-center text-slate-500">No payments match these filters.</p>:<div className="space-y-2 max-h-[58vh] overflow-y-auto">{visible.map(p=><button key={p.id} type="button" onClick={()=>setSelected(p.id)} className={'w-full text-left rounded-2xl border p-3 '+(p.id===chosen?.id?'border-violet-400 bg-violet-50 ring-1 ring-violet-200':'border-slate-200 bg-white hover:bg-slate-50')}><span className="flex justify-between gap-3"><span className="min-w-0"><b className="block truncate text-sm">{supplierById.get(p.supplier_id)?.name||'Supplier'}</b><span className="block text-xs text-slate-500 mt-1">{dateLabel(p.payment_date)} · {p.payment_mode.replaceAll('_',' ')}{p.is_advance?' · Advance':''}</span></span><b className="shrink-0 text-violet-700">{money(Number(p.amount))}</b></span><span className="block text-[11px] text-slate-400 mt-2">Voucher {p.id.slice(0,8).toUpperCase()}</span></button>)}</div>}
 <div className="flex items-center justify-between gap-2"><p className="text-xs text-slate-400">Up to 500 recent records.</p><button onClick={exportCsv} disabled={!visible.length} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm disabled:opacity-50"><Download size={15}/>CSV</button></div></section>
 <section className="space-y-3">{chosen?<><div className="flex flex-wrap gap-2 no-print"><button onClick={()=>window.print()} className="flex-1 rounded-xl bg-violet-700 text-white font-semibold px-4 py-3 inline-flex justify-center items-center gap-2"><Printer size={17}/>Print / Save PDF</button><button onClick={()=>void share()} className="rounded-xl border bg-white px-4 py-3 inline-flex justify-center items-center gap-2"><Share2 size={17}/>Share</button></div>
 <article className="voucher-paper card p-5 md:p-8" aria-label="Supplier payment voucher"><div className="flex justify-between items-start gap-3 border-b-2 border-slate-800 pb-4"><div><p className="text-xs uppercase tracking-[.18em] text-violet-700 font-bold">Supplier payment voucher</p><h2 className="text-xl md:text-2xl font-extrabold mt-1">Guru Kalyanam</h2><p className="text-sm text-slate-500">School Supply Ops</p></div><div className="text-right"><ReceiptText size={28} className="ml-auto text-violet-700"/><p className="text-xs text-slate-500 mt-2">Voucher no.</p><p className="font-bold tracking-wider">{chosen.id.slice(0,8).toUpperCase()}</p></div></div>
 <div className="py-5 border-b border-dashed border-slate-300"><p className="text-xs text-slate-500">Paid to</p><h3 className="text-lg font-bold mt-1 break-words">{supplier?.name||'Supplier'}</h3>{supplier?.company&&<p className="text-sm text-slate-500 mt-1">{supplier.company}</p>}{supplier?.address&&<p className="text-sm text-slate-500 mt-1 whitespace-pre-line">{supplier.address}</p>}{supplier?.phone&&<p className="text-sm text-slate-500 mt-1">Phone: {supplier.phone}</p>}</div>
 <div className="py-5 grid grid-cols-2 gap-4 border-b border-dashed border-slate-300"><div><p className="text-xs text-slate-500">Payment date</p><p className="font-semibold mt-1">{dateLabel(chosen.payment_date)}</p></div><div><p className="text-xs text-slate-500">Payment method</p><p className="font-semibold mt-1">{chosen.payment_mode.replaceAll('_',' ')}</p></div><div><p className="text-xs text-slate-500">Payment type</p><p className="font-semibold mt-1">{chosen.is_advance?'Advance / supplier credit':'Purchase payment'}</p></div>{purchase&&<div><p className="text-xs text-slate-500">Against purchase</p><p className="font-semibold mt-1">Purchase order #{purchase.purchase_number}</p></div>}{chosen.reference_number&&<div className="col-span-2"><p className="text-xs text-slate-500">Transaction reference</p><p className="font-semibold mt-1 break-all">{chosen.reference_number}</p></div>}</div>
 <div className="py-5"><p className="text-xs text-slate-500">Amount paid</p><p className="text-3xl md:text-4xl font-extrabold text-violet-700 mt-1">{money(Number(chosen.amount))}</p>{chosen.notes&&<p className="text-sm text-slate-500 mt-2 whitespace-pre-line">Notes: {chosen.notes}</p>}</div>
 <div className="mt-6 pt-4 border-t border-slate-300 flex justify-between items-end gap-4"><p className="text-xs text-slate-500 max-w-[65%]">This voucher acknowledges the supplier payment recorded in the system. Retain it with the purchase records.</p><div className="text-center min-w-28"><div className="border-t border-slate-500 pt-2 text-xs">Authorized signature</div></div></div><p className="text-[10px] text-slate-400 mt-5 text-center">Generated from recorded supplier payment data · ID {chosen.id}</p></article></>:<div className="card p-10 text-center text-slate-500">Select a payment to preview its voucher.</div>}</section>
 </div></div></main><style jsx global>{`@media print{@page{size:A4;margin:14mm}body{background:white!important;color:#111827!important}.no-print,.app-desktop-nav,.app-mobile-nav,.mobile-bottom-nav,.mobile-menu-panel,.mobile-menu-backdrop{display:none!important}main{padding:0!important;margin:0!important;overflow:visible!important}main>div{max-width:none!important;margin:0!important}main>div>div{display:block!important}.voucher-paper{box-shadow:none!important;border:1px solid #d1d5db!important;border-radius:0!important;padding:12mm!important;max-width:none!important;break-inside:avoid}.voucher-paper *{-webkit-print-color-adjust:exact;print-color-adjust:exact}}`}</style></div>
}
