'use client';

import { useEffect, useMemo, useState } from 'react';
import { Download, Filter, Pencil, Plus, RefreshCw, Trash2, Wallet } from 'lucide-react';
import AppNav from '@/components/AppNav';
import { createClient } from '@/lib/supabase';

type Expense = { id:string; expense_date:string; category:string; description:string; amount:number; payment_mode:string; reference_number:string|null; notes:string|null; created_at:string };
const categories = [
  ['TRAVEL','Travel'],['FUEL','Fuel'],['FOOD','Meals & refreshments'],['OFFICE_SUPPLIES','Office supplies'],
  ['PHONE_INTERNET','Phone & internet'],['BANK_CHARGES','Bank charges'],['REPAIRS','Repairs & maintenance'],
  ['SALARIES','Salaries / wages'],['RENT','Rent'],['OTHER','Other']
];
const modes = ['CASH','UPI','BANK_TRANSFER','CHEQUE','OTHER'];
const money=(n:number)=>'₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const csv=(rows:any[][])=>rows.map(row=>row.map(v=>{const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}).join(',')).join('\n');

export default function ExpensesPage(){
 const supabase=createClient();
 const [rows,setRows]=useState<Expense[]>([]);
 const [editing,setEditing]=useState('');
 const [date,setDate]=useState(today()),[category,setCategory]=useState('TRAVEL'),[description,setDescription]=useState('');
 const [amount,setAmount]=useState(''),[mode,setMode]=useState('UPI'),[reference,setReference]=useState(''),[notes,setNotes]=useState('');
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[filterCategory,setFilterCategory]=useState(''),[filterMode,setFilterMode]=useState(''),[query,setQuery]=useState('');
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);setError('');const {data,error:e}=await supabase.from('business_expenses').select('id,expense_date,category,description,amount,payment_mode,reference_number,notes,created_at').order('expense_date',{ascending:false}).order('created_at',{ascending:false}).limit(1000);if(e)setError(e.message);setRows((data||[]) as Expense[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>rows.filter(r=>{const q=query.trim().toLowerCase();return (!from||r.expense_date>=from)&&(!to||r.expense_date<=to)&&(!filterCategory||r.category===filterCategory)&&(!filterMode||r.payment_mode===filterMode)&&(!q||r.description.toLowerCase().includes(q)||(r.reference_number||'').toLowerCase().includes(q)||(r.notes||'').toLowerCase().includes(q))}),[rows,from,to,filterCategory,filterMode,query]);
 const total=visible.reduce((s,r)=>s+Number(r.amount||0),0);
 const reset=()=>{setEditing('');setDate(today());setCategory('TRAVEL');setDescription('');setAmount('');setMode('UPI');setReference('');setNotes('')};
 const save=async()=>{const n=Number(amount);if(!description.trim()||description.trim().length<2){setError('Enter an expense description (at least 2 characters).');return}if(!Number.isFinite(n)||n<=0){setError('Enter an amount greater than zero.');return}if(!date){setError('Choose the expense date.');return}setSaving(true);setError('');setMessage('');const {data:{user}}=await supabase.auth.getUser();const payload={expense_date:date,category,description:description.trim(),amount:n,payment_mode:mode,reference_number:reference.trim()||null,notes:notes.trim()||null,...(!editing?{created_by:user?.id||null}:{})};const result=editing?await supabase.from('business_expenses').update(payload).eq('id',editing):await supabase.from('business_expenses').insert(payload);if(result.error){setError(result.error.message);setSaving(false);return}setMessage(editing?'Expense updated.':'Expense recorded.');reset();setSaving(false);await load()};
 const edit=(r:Expense)=>{setEditing(r.id);setDate(r.expense_date);setCategory(r.category);setDescription(r.description);setAmount(String(r.amount));setMode(r.payment_mode);setReference(r.reference_number||'');setNotes(r.notes||'');setError('');setMessage('')};
 const remove=async(id:string)=>{if(!window.confirm('Delete this expense record? This cannot be undone.'))return;setError('');const {error:e}=await supabase.from('business_expenses').delete().eq('id',id);if(e){setError(e.message);return}if(editing===id)reset();setMessage('Expense deleted.');await load()};
 const exportCsv=()=>{const blob=new Blob(['\ufeff'+csv([['Date','Category','Description','Amount','Payment mode','Reference','Notes'],...visible.map(r=>[r.expense_date,categories.find(c=>c[0]===r.category)?.[1]||r.category,r.description,r.amount,r.payment_mode,r.reference_number,r.notes])])],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='guru-kalyanam-expenses.csv';a.click();URL.revokeObjectURL(url)};
 return <div className="min-h-screen flex bg-slate-50"><AppNav/><main className="flex-1 min-w-0 p-4 md:p-8"><div className="max-w-7xl mx-auto space-y-6">
  <header className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><p className="text-sm text-slate-500">Phase 38 · Cash flow</p><h1 className="text-3xl font-bold">Business Expenses</h1><p className="text-slate-500 mt-1">Track operating costs separately from school collections and supplier payments.</p></div><button onClick={()=>void load()} className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold inline-flex items-center gap-2"><RefreshCw size={16}/>Refresh</button></header>
  <section className="grid grid-cols-2 lg:grid-cols-3 gap-3"><div className="card p-4"><p className="text-xs text-slate-500">Filtered expenses</p><p className="text-2xl font-bold mt-1">{money(total)}</p></div><div className="card p-4"><p className="text-xs text-slate-500">Records</p><p className="text-2xl font-bold mt-1">{visible.length}</p></div><div className="card p-4 col-span-2 lg:col-span-1"><p className="text-xs text-slate-500">Average expense</p><p className="text-2xl font-bold mt-1">{money(visible.length?total/visible.length:0)}</p></div></section>
  {error&&<div role="alert" className="rounded-xl bg-red-50 text-red-700 p-3 text-sm">{error}</div>}{message&&<div role="status" className="rounded-xl bg-emerald-50 text-emerald-700 p-3 text-sm">{message}</div>}
  <div className="grid xl:grid-cols-[360px_1fr] gap-5 items-start">
   <section className="card p-5 space-y-3"><h2 className="font-bold flex items-center gap-2"><Wallet size={18}/>{editing?'Edit expense':'Record an expense'}</h2>
    <label className="block text-sm">Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full border rounded-xl px-3 py-2"/></label>
    <label className="block text-sm">Category<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 w-full border rounded-xl px-3 py-2">{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <label className="block text-sm">Description<input value={description} onChange={e=>setDescription(e.target.value)} maxLength={240} placeholder="e.g. School visit travel" className="mt-1 w-full border rounded-xl px-3 py-2"/></label>
    <label className="block text-sm">Amount (₹)<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00" className="mt-1 w-full border rounded-xl px-3 py-2"/></label>
    <label className="block text-sm">Payment mode<select value={mode} onChange={e=>setMode(e.target.value)} className="mt-1 w-full border rounded-xl px-3 py-2">{modes.map(v=><option key={v} value={v}>{v.replace('_',' ')}</option>)}</select></label>
    <label className="block text-sm">Reference (optional)<input value={reference} onChange={e=>setReference(e.target.value)} maxLength={120} placeholder="UPI / receipt reference" className="mt-1 w-full border rounded-xl px-3 py-2"/></label>
    <label className="block text-sm">Notes (optional)<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={2} maxLength={1000} className="mt-1 w-full border rounded-xl px-3 py-2" placeholder="Additional details"/></label>
    <div className="flex gap-2"><button disabled={saving} onClick={()=>void save()} className="flex-1 rounded-xl bg-slate-900 text-white p-3 font-semibold inline-flex items-center justify-center gap-2 disabled:opacity-50">{editing?<Pencil size={16}/>:<Plus size={16}/>} {saving?'Saving…':editing?'Save changes':'Record expense'}</button>{editing&&<button onClick={reset} className="rounded-xl border px-3">Cancel</button>}</div>
   </section>
   <section className="card p-4 md:p-5 space-y-4"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2"><div><h2 className="font-bold">Expense history</h2><p className="text-sm text-slate-500">Showing up to the latest 1,000 records.</p></div><button onClick={exportCsv} disabled={!visible.length} className="rounded-xl border px-3 py-2 text-sm inline-flex items-center gap-2 disabled:opacity-50"><Download size={16}/>Export CSV</button></div>
    <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search description, reference…" className="border rounded-xl px-3 py-2"/><input type="date" value={from} onChange={e=>setFrom(e.target.value)} aria-label="From date" className="border rounded-xl px-3 py-2"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} aria-label="To date" className="border rounded-xl px-3 py-2"/><select value={filterCategory} onChange={e=>setFilterCategory(e.target.value)} className="border rounded-xl px-3 py-2"><option value="">All categories</option>{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={filterMode} onChange={e=>setFilterMode(e.target.value)} className="border rounded-xl px-3 py-2"><option value="">All payment modes</option>{modes.map(v=><option key={v} value={v}>{v.replace('_',' ')}</option>)}</select><button onClick={()=>{setFrom('');setTo('');setFilterCategory('');setFilterMode('');setQuery('')}} className="border rounded-xl px-3 py-2 inline-flex items-center justify-center gap-2"><Filter size={15}/>Clear filters</button></div>
    {loading?<p className="text-slate-500 py-8 text-center">Loading expenses…</p>:!visible.length?<p className="text-slate-500 py-8 text-center">No expenses match these filters yet.</p>:<div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr className="border-b text-slate-500"><th className="py-3 pr-3">Date / Description</th><th className="py-3 px-3">Category</th><th className="py-3 px-3">Mode</th><th className="py-3 px-3 text-right">Amount</th><th className="py-3 pl-3 text-right">Actions</th></tr></thead><tbody>{visible.map(r=><tr key={r.id} className="border-b last:border-0 align-top"><td className="py-3 pr-3"><b className="block">{r.description}</b><span className="text-xs text-slate-500">{r.expense_date}{r.reference_number?' · '+r.reference_number:''}</span>{r.notes&&<span className="block text-xs text-slate-500 mt-1">{r.notes}</span>}</td><td className="py-3 px-3 whitespace-nowrap">{categories.find(c=>c[0]===r.category)?.[1]||r.category}</td><td className="py-3 px-3 whitespace-nowrap">{r.payment_mode.replace('_',' ')}</td><td className="py-3 px-3 text-right font-semibold whitespace-nowrap">{money(Number(r.amount))}</td><td className="py-3 pl-3"><div className="flex justify-end gap-2"><button aria-label={'Edit '+r.description} onClick={()=>edit(r)} className="rounded-lg border p-2"><Pencil size={15}/></button><button aria-label={'Delete '+r.description} onClick={()=>void remove(r.id)} className="rounded-lg border p-2 text-red-600"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>}
   </section>
  </div>
 </div></main></div>;
}
