'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { ArrowLeft, History, LocateFixed, MapPin, Phone, Plus, Trash2 } from 'lucide-react';
import AppNav from '@/components/AppNav';
import { createClient } from '@/lib/supabase';

export default function SchoolDetail(){
 const {id}=useParams<{id:string}>(),client=createClient();
 const [school,setSchool]=useState<any>(null),[contacts,setContacts]=useState<any[]>([]),[visits,setVisits]=useState<any[]>([]),[location,setLocation]=useState<any>(null),[active,setActive]=useState<any>(null);
 const [contact,setContact]=useState({name:'',phone:'',whatsapp_number:'',designation:''}),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const [s,c,v,l]=await Promise.all([
  client.from('schools').select('*').eq('id',id).single(),client.from('school_contacts').select('*').eq('school_id',id).order('is_primary',{ascending:false}),
  client.from('school_visits').select('*').eq('school_id',id).order('started_at',{ascending:false}).limit(8),client.from('locations').select('*').eq('school_id',id).order('captured_at',{ascending:false}).limit(1)
 ]);if(s.error)setError(s.error.message);setSchool(s.data);setContacts(c.data||[]);setVisits(v.data||[]);setLocation(l.data?.[0]||null);setActive((v.data||[]).find((x:any)=>!x.ended_at)||null);setLoading(false)};
 useEffect(()=>{if(id)load()},[id]);
 const saveLocation=()=>navigator.geolocation?.getCurrentPosition(async p=>{const old=await client.from('locations').update({is_current:false}).eq('school_id',id).eq('is_current',true);if(old.error){setError(old.error.message);return}const r=await client.from('locations').insert({school_id:id,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_meters:p.coords.accuracy});if(r.error)setError(r.error.message);else{await client.from('schools').update({latitude:p.coords.latitude,longitude:p.coords.longitude}).eq('id',id);load()}},e=>setError(e.message),{enableHighAccuracy:true});
 const start=()=>navigator.geolocation?.getCurrentPosition(async p=>{const r=await client.from('school_visits').insert({school_id:id,started_at:new Date().toISOString(),latitude:p.coords.latitude,longitude:p.coords.longitude,purpose:'GENERAL'}).select().single();if(r.error)setError(r.error.message);else{await client.from('schools').update({last_visit_at:new Date().toISOString()}).eq('id',id);load()}},e=>setError(e.message),{enableHighAccuracy:true});
 const end=async()=>{if(!active)return;const r=await client.from('school_visits').update({ended_at:new Date().toISOString()}).eq('id',active.id);if(r.error)setError(r.error.message);else load()};
 const saveContact=async(e:any)=>{e.preventDefault();const r=editing?await client.from('school_contacts').update(contact).eq('id',editing):await client.from('school_contacts').insert({...contact,school_id:id});if(r.error)setError(r.error.message);else{setContact({name:'',phone:'',whatsapp_number:'',designation:''});setEditing(null);load()}};
 const delContact=async(cid:string)=>{const r=await client.from('school_contacts').delete().eq('id',cid);if(r.error)setError(r.error.message);else load()};
 if(loading)return <main className="p-8">Loading…</main>;
 if(!school)return <main className="p-8">School not found.</main>;
 const bbox=school.latitude&&school.longitude?(school.longitude-0.004)+','+(school.latitude-0.004)+','+(school.longitude+0.004)+','+(school.latitude+0.004):null;
 return <div className="min-h-screen flex bg-slate-50"><AppNav/><main className="flex-1 p-4 md:p-8"><div className="max-w-6xl mx-auto">
  <Link href="/schools" className="text-sm text-slate-500 flex items-center gap-1 mb-4"><ArrowLeft size={15}/>Back to schools</Link>
  <header className="mb-6 flex flex-col md:flex-row md:items-end justify-between gap-3"><div><p className="text-sm text-slate-500">{school.school_type} · {school.status}</p><h1 className="text-3xl font-bold">{school.name}</h1><p className="text-slate-600">{school.address||'No address'}{school.district?' · '+school.district:''}</p></div><div className="flex flex-wrap gap-2"><Link href={'/schools/'+id+'/timeline'} className="rounded-xl border bg-white px-4 py-3 flex gap-2 items-center"><History size={17}/>School timeline</Link>{active?<button onClick={end} className="rounded-xl bg-amber-600 text-white px-4 py-3 font-semibold">End active visit</button>:<button onClick={start} className="rounded-xl bg-emerald-600 text-white px-4 py-3 font-semibold">Start visit</button>}<button onClick={saveLocation} className="rounded-xl border bg-white px-4 py-3 flex gap-2 items-center"><LocateFixed size={17}/>Save location</button></div></header>
  {error&&<p className="mb-4 rounded-xl bg-red-50 text-red-700 p-3 text-sm">{error}</p>}
  <div className="grid lg:grid-cols-3 gap-5">
   <section className="card p-5 lg:col-span-2"><h2 className="font-bold mb-4">Location</h2>{bbox?<iframe title="School map" className="w-full h-72 rounded-xl border" src={'https://www.openstreetmap.org/export/embed.html?bbox='+bbox+'&layer=mapnik&marker='+school.latitude+','+school.longitude}/>:<div className="h-40 grid place-items-center bg-slate-50 rounded-xl text-slate-500">No coordinates yet. Save the current location.</div>}{location&&<p className="text-xs text-slate-500 mt-3">Last GPS capture: {new Date(location.captured_at).toLocaleString()} · ±{Math.round(location.accuracy_meters||0)}m</p>}</section>
   <section className="card p-5"><h2 className="font-bold mb-4">School details</h2><dl className="space-y-3 text-sm"><div><dt className="text-slate-500">UDISE</dt><dd>{school.udise_code||'—'}</dd></div><div><dt className="text-slate-500">Principal</dt><dd>{school.principal_name||'—'}</dd></div><div><dt className="text-slate-500">Last visit</dt><dd>{school.last_visit_at?new Date(school.last_visit_at).toLocaleString():'—'}</dd></div></dl>{school.latitude&&school.longitude&&<a target="_blank" rel="noreferrer" href={'https://www.google.com/maps?q='+school.latitude+','+school.longitude} className="mt-5 rounded-xl border px-3 py-2.5 flex items-center gap-2 text-sm"><MapPin size={16}/>Open in Google Maps</a>}</section>
   <section className="card p-5"><h2 className="font-bold mb-4">Contacts</h2><form onSubmit={saveContact} className="space-y-2 mb-5">{['name','phone','whatsapp_number','designation'].map(k=><input key={k} required={k==='name'} placeholder={k.replace('_',' ')} value={(contact as any)[k]} onChange={e=>setContact({...contact,[k]:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"/>)}<button className="w-full rounded-xl bg-slate-900 text-white py-2.5 flex justify-center gap-2"><Plus size={17}/>{editing?'Update contact':'Add contact'}</button></form><div className="space-y-3">{contacts.map(c=><div key={c.id} className="border rounded-xl p-3 flex justify-between gap-2"><div><b>{c.name}</b><p className="text-xs text-slate-500">{c.designation||'Contact'}</p>{c.phone&&<p className="text-sm mt-1 flex gap-1 items-center"><Phone size={13}/>{c.phone}</p>}</div><div className="flex"><button onClick={()=>{setEditing(c.id);setContact({name:c.name,phone:c.phone||'',whatsapp_number:c.whatsapp_number||'',designation:c.designation||''})}} className="text-xs px-2">Edit</button><button onClick={()=>delContact(c.id)} className="text-red-600 px-2"><Trash2 size={15}/></button></div></div>)}</div></section>
   <section className="card p-5 lg:col-span-2"><h2 className="font-bold mb-4">Recent visits</h2>{visits.length===0?<p className="text-slate-500 text-sm">No visits recorded yet.</p>:<div className="divide-y">{visits.map(v=><div key={v.id} className="py-3 flex justify-between"><div><b>{new Date(v.started_at).toLocaleString()}</b><p className="text-sm text-slate-500">{v.purpose}</p></div><span className="text-xs">{v.ended_at?'Completed':'Active'}</span></div>)}</div>}</section>
  </div>
 </div></main></div>;
}
