'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Map, School, ClipboardList, Package, Truck, IndianRupee, CheckSquare, BarChart3, LayoutDashboard, Users, Bell, Boxes, CalendarClock, FileText, ListTodo, MessageCircle, ChevronRight, Sparkles, Settings, WalletCards, TrendingUp, AlertTriangle } from 'lucide-react';
import GlobalSearch from '@/components/GlobalSearch';

const items = [
  ['/', 'Dashboard', LayoutDashboard], ['/work-queue', 'Work Queue', ListTodo], ['/schools', 'Schools', School], ['/visits', 'Visits', CheckSquare], ['/follow-ups', 'Follow-ups', CalendarClock], ['/map', 'Map', Map], ['/orders', 'Orders', ClipboardList], ['/pipeline', 'Pipeline', ClipboardList], ['/templates', 'Templates', ClipboardList], ['/products', 'Products', Package], ['/inventory', 'Inventory', Boxes], ['/suppliers', 'Suppliers', Users], ['/purchases', 'Purchases', ClipboardList], ['/receivables', 'School Receivables', AlertTriangle], ['/statements', 'School Statements', FileText], ['/supplier-payments', 'Supplier Payments', WalletCards], ['/supplier-statements', 'Supplier Statements', FileText], ['/supplier-performance', 'Supplier Performance', TrendingUp], ['/expenses', 'Expenses', WalletCards], ['/deliveries', 'Deliveries', Truck], ['/payments', 'Payments', IndianRupee], ['/invoices', 'GST Invoices', FileText], ['/whatsapp', 'WhatsApp', MessageCircle], ['/reminders', 'Reminders', CheckSquare], ['/tasks', 'Tasks', CheckSquare], ['/notifications', 'Notifications', Bell], ['/reports', 'Reports', BarChart3], ['/insights', 'Monthly Insights', TrendingUp], ['/timeline', 'Timeline', ClipboardList], ['/settings', 'Business Settings', Settings],
] as const;
const navColors:Record<string,string>={Dashboard:'bg-sky-100 text-sky-700',Schools:'bg-blue-100 text-blue-700',Visits:'bg-emerald-100 text-emerald-700',Map:'bg-cyan-100 text-cyan-700',Orders:'bg-violet-100 text-violet-700',Templates:'bg-purple-100 text-purple-700',Products:'bg-indigo-100 text-indigo-700',Inventory:'bg-teal-100 text-teal-700',Suppliers:'bg-amber-100 text-amber-700',Purchases:'bg-orange-100 text-orange-700','Supplier Payments':'bg-violet-100 text-violet-700','Supplier Statements':'bg-sky-100 text-sky-700','Supplier Performance':'bg-amber-100 text-amber-700',Expenses:'bg-rose-100 text-rose-700',Deliveries:'bg-lime-100 text-lime-700',Payments:'bg-pink-100 text-pink-700',Reminders:'bg-yellow-100 text-yellow-700',Tasks:'bg-green-100 text-green-700',Notifications:'bg-rose-100 text-rose-700',Reports:'bg-fuchsia-100 text-fuchsia-700','Monthly Insights':'bg-emerald-100 text-emerald-700','School Receivables':'bg-amber-100 text-amber-700','School Statements':'bg-sky-100 text-sky-700','Work Queue':'bg-emerald-100 text-emerald-700',Timeline:'bg-slate-100 text-slate-700','Follow-ups':'bg-amber-100 text-amber-700','GST Invoices':'bg-cyan-100 text-cyan-700','Business Settings':'bg-slate-100 text-slate-700',WhatsApp:'bg-emerald-100 text-emerald-700'};
const mobileItems=items.filter(([href])=>['/','/schools','/orders','/payments','/supplier-payments','/reports'].includes(href));
const navGroup=(href:string)=>href==='/'||href==='/work-queue'?'OVERVIEW':['/schools','/visits','/follow-ups','/map'].includes(href)?'FIELD OPERATIONS':['/orders','/pipeline','/templates'].includes(href)?'SALES & ORDERS':['/products','/inventory','/suppliers','/purchases'].includes(href)?'CATALOG & SUPPLIERS':['/supplier-payments','/supplier-statements','/supplier-performance','/receivables','/statements','/expenses','/deliveries','/payments','/invoices'].includes(href)?'MONEY & FULFILMENT':['/whatsapp','/reminders','/tasks','/notifications'].includes(href)?'COMMUNICATION & TASKS':'INSIGHTS & SETTINGS';

export default function AppNav(){
 const pathname=usePathname();
 const activeFor=(href:string)=>pathname===href||(href!=='/'&&pathname.startsWith(href));
 return <>
  <aside className="app-desktop-nav">
   <Link href="/" className="brand-mark"><span className="brand-logo"><School size={21}/></span><span><b>Guru Kalyanam</b><small>School Supply Workspace</small></span><span className="brand-spark"><Sparkles size={15}/></span></Link>
   <div className="nav-search"><GlobalSearch/></div>
   <div className="nav-section-heading"><span className="nav-label">YOUR WORKSPACE</span><span className="nav-count">{items.length}</span></div>
   <nav className="nav-list">{items.map(([href,label,Icon],index)=>{const active=activeFor(href);const group=navGroup(href);const previous=index?navGroup(items[index-1][0]):'';return <div key={href} className="nav-entry">{group!==previous&&<div className="nav-group-label">{group}</div>}<Link href={href} aria-current={active?'page':undefined} className={['nav-item',active?'nav-item-active':''].join(' ')}><span className={['nav-item-icon',active?(navColors[label]||'bg-emerald-100 text-emerald-700'):''].join(' ')}><Icon size={18} strokeWidth={active?2.4:1.9}/></span><span className="nav-item-label">{label}</span>{active&&<ChevronRight className="nav-chevron" size={15}/>}</Link></div>})}</nav>
   <div className="workspace-badge"><span className="workspace-dot"/><span><b>Workspace ready</b><small>All your operations, together</small></span></div>
  </aside>
  <header className="app-mobile-nav">
   <div className="mobile-topline"><Link href="/" className="mobile-brand"><span className="brand-logo"><School size={20}/></span><span><b>Guru Kalyanam</b><small>School Supply Ops</small></span></Link><div className="flex items-center gap-2"><Link href="/supplier-statements" className="mobile-notification" aria-label="Supplier statements"><FileText size={20}/></Link><Link href="/supplier-performance" className="mobile-notification" aria-label="Supplier performance"><TrendingUp size={20}/></Link><Link href="/receivables" className="mobile-notification" aria-label="School receivables"><AlertTriangle size={20}/></Link><Link href="/statements" className="mobile-notification" aria-label="School statements"><FileText size={20}/></Link><Link href="/insights" className="mobile-notification" aria-label="Monthly insights"><TrendingUp size={20}/></Link><Link href="/expenses" className="mobile-notification" aria-label="Business expenses"><WalletCards size={20}/></Link><Link href="/notifications" className="mobile-notification" aria-label="Notifications"><Bell size={20}/><i/></Link></div></div>
   <div className="mobile-search"><GlobalSearch/></div>
  </header>
  <nav className="mobile-bottom-nav" aria-label="Main navigation">{mobileItems.map(([href,label,Icon])=>{const active=activeFor(href);return <Link key={href} href={href} aria-current={active?'page':undefined} className={['mobile-dock-item',active?'mobile-dock-active':''].join(' ')}><span className="mobile-dock-icon"><Icon size={20} strokeWidth={active?2.5:2}/></span><span>{label==='Payments'?'Money':label==='Supplier Payments'?'Supplier pay':label}</span></Link>})}<Link href="/work-queue" className={['mobile-dock-item',activeFor('/work-queue')?'mobile-dock-active':''].join(' ')}><span className="mobile-dock-icon"><ListTodo size={20}/></span><span>More</span></Link></nav>
 </>;
}
