-- Phase 1: core business schema for School Supply Ops.
-- Applied to the connected Supabase project as migration: phase_1_core_schema.
create extension if not exists pgcrypto;

do $$ begin
  create type public.user_role as enum ('OWNER','ADMIN','SALES_PERSON','DELIVERY_PERSON','VIEWER');
exception when duplicate_object then null; end $$;
do $$ begin create type public.school_status as enum ('ACTIVE','INACTIVE','ARCHIVED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.school_type as enum ('PRIMARY','UPPER_PRIMARY','SECONDARY','SENIOR_SECONDARY','OTHER'); exception when duplicate_object then null; end $$;
do $$ begin create type public.order_status as enum ('NEW','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','PARTIALLY_DELIVERED','CANCELLED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_status as enum ('UNPAID','PARTIAL','PAID','OVERDUE'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_mode as enum ('CASH','UPI','BANK_TRANSFER','CHEQUE','OTHER'); exception when duplicate_object then null; end $$;
do $$ begin create type public.delivery_status as enum ('SCHEDULED','PREPARING','OUT_FOR_DELIVERY','DELIVERED','FAILED','RESCHEDULED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.visit_purpose as enum ('SALES','DELIVERY','PAYMENT_COLLECTION','FOLLOW_UP','GENERAL'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, phone text, role public.user_role not null default 'VIEWER', business_name text, avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.schools (id uuid primary key default gen_random_uuid(), name text not null, udise_code text, address text, village_area text, district text, state text default 'Uttar Pradesh', latitude double precision, longitude double precision, maps_url text, school_type public.school_type not null default 'OTHER', principal_name text, notes text, status public.school_status not null default 'ACTIVE', tags text[] not null default '{}', custom_fields jsonb not null default '{}', last_visit_at timestamptz, next_follow_up_at timestamptz, created_by uuid references public.profiles(id) on delete set null, updated_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.school_contacts (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, phone text, whatsapp_number text, designation text, notes text, is_primary boolean not null default false, created_by uuid references public.profiles(id) on delete set null, updated_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.locations (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, latitude double precision not null, longitude double precision not null, accuracy_meters double precision, captured_at timestamptz not null default now(), source text not null default 'gps', is_current boolean not null default true, captured_by uuid references public.profiles(id) on delete set null);
create table if not exists public.school_visits (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, visited_by uuid references public.profiles(id) on delete set null, started_at timestamptz not null default now(), ended_at timestamptz, latitude double precision, longitude double precision, person_met text, purpose public.visit_purpose not null default 'GENERAL', order_received boolean not null default false, payment_collected boolean not null default false, follow_up_required boolean not null default false, notes text, created_at timestamptz not null default now());
create table if not exists public.product_categories (id uuid primary key default gen_random_uuid(), name text not null unique, created_at timestamptz not null default now());
create table if not exists public.suppliers (id uuid primary key default gen_random_uuid(), name text not null, company text, phone text, whatsapp text, address text, notes text, outstanding_amount numeric(14,2) not null default 0, created_by uuid references public.profiles(id) on delete set null, updated_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.products (id uuid primary key default gen_random_uuid(), category_id uuid references public.product_categories(id) on delete set null, name text not null, sku text, unit text not null default 'piece', purchase_price numeric(14,2) not null default 0, selling_price numeric(14,2) not null default 0, tax_rate numeric(5,2) not null default 0, current_stock numeric(14,3) not null default 0, minimum_stock numeric(14,3) not null default 0, supplier_id uuid references public.suppliers(id) on delete set null, active boolean not null default true, notes text, custom_fields jsonb not null default '{}', created_by uuid references public.profiles(id) on delete set null, updated_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.order_templates (id uuid primary key default gen_random_uuid(), name text not null, description text, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.order_template_items (id uuid primary key default gen_random_uuid(), template_id uuid not null references public.order_templates(id) on delete cascade, product_id uuid references public.products(id) on delete set null, product_name text not null, default_quantity numeric(14,3) not null default 1, unit text not null default 'piece', default_price numeric(14,2) not null default 0, sort_order integer not null default 0);
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), order_number bigint generated always as identity unique, school_id uuid not null references public.schools(id), contact_id uuid references public.school_contacts(id) on delete set null, order_date date not null default current_date, expected_delivery_date date, status public.order_status not null default 'NEW', payment_status public.payment_status not null default 'UNPAID', subtotal numeric(14,2) not null default 0, discount numeric(14,2) not null default 0, tax_amount numeric(14,2) not null default 0, total numeric(14,2) not null default 0, paid_amount numeric(14,2) not null default 0, notes text, created_by uuid references public.profiles(id) on delete set null, updated_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id) on delete set null, product_name text not null, quantity numeric(14,3) not null, unit text not null default 'piece', unit_price numeric(14,2) not null default 0, discount numeric(14,2) not null default 0, tax_rate numeric(5,2) not null default 0, line_total numeric(14,2) not null default 0, custom_item boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.deliveries (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id), school_id uuid not null references public.schools(id), responsible_user_id uuid references public.profiles(id) on delete set null, scheduled_date date, scheduled_time time, status public.delivery_status not null default 'SCHEDULED', delivered_at timestamptz, delivery_notes text, proof_attachment_id uuid, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.inventory (product_id uuid primary key references public.products(id) on delete cascade, incoming_stock numeric(14,3) not null default 0, reserved_stock numeric(14,3) not null default 0, available_stock numeric(14,3) not null default 0, updated_at timestamptz not null default now());
create table if not exists public.inventory_transactions (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id), quantity numeric(14,3) not null, transaction_type text not null, reference_type text, reference_id uuid, notes text, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.purchases (id uuid primary key default gen_random_uuid(), supplier_id uuid not null references public.suppliers(id), purchase_number bigint generated always as identity unique, purchase_date date not null default current_date, expected_arrival_date date, status text not null default 'ORDERED', total numeric(14,2) not null default 0, paid_amount numeric(14,2) not null default 0, notes text, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.purchase_items (id uuid primary key default gen_random_uuid(), purchase_id uuid not null references public.purchases(id) on delete cascade, product_id uuid references public.products(id) on delete set null, product_name text not null, quantity numeric(14,3) not null, unit text not null default 'piece', unit_cost numeric(14,2) not null default 0, line_total numeric(14,2) not null default 0);
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id), order_id uuid references public.orders(id) on delete set null, amount numeric(14,2) not null, payment_date date not null default current_date, payment_mode public.payment_mode not null, reference_number text, notes text, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.reminders (id uuid primary key default gen_random_uuid(), title text not null, description text, due_at timestamptz not null, school_id uuid references public.schools(id) on delete cascade, order_id uuid references public.orders(id) on delete cascade, priority text not null default 'MEDIUM', repeat_rule text, completed boolean not null default false, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), title text not null, description text, due_at timestamptz, school_id uuid references public.schools(id) on delete cascade, order_id uuid references public.orders(id) on delete cascade, priority text not null default 'MEDIUM', completed boolean not null default false, assigned_to uuid references public.profiles(id) on delete set null, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, title text not null, body text, type text, read_at timestamptz, related_school_id uuid references public.schools(id) on delete cascade, related_order_id uuid references public.orders(id) on delete cascade, created_at timestamptz not null default now());
create table if not exists public.attachments (id uuid primary key default gen_random_uuid(), school_id uuid references public.schools(id) on delete cascade, order_id uuid references public.orders(id) on delete cascade, visit_id uuid references public.school_visits(id) on delete cascade, storage_path text not null, file_name text not null, mime_type text, size_bytes bigint, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.activity_logs (id bigint generated always as identity primary key, actor_id uuid references public.profiles(id) on delete set null, entity_type text not null, entity_id uuid, action text not null, old_data jsonb, new_data jsonb, created_at timestamptz not null default now());

create index if not exists schools_name_idx on public.schools(name);
create index if not exists schools_district_idx on public.schools(district);
create index if not exists school_contacts_school_idx on public.school_contacts(school_id);
create index if not exists school_visits_school_idx on public.school_visits(school_id, started_at desc);
create index if not exists products_name_idx on public.products(name);
create index if not exists orders_school_idx on public.orders(school_id, order_date desc);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists deliveries_date_idx on public.deliveries(scheduled_date, status);
create index if not exists payments_school_idx on public.payments(school_id, payment_date desc);
create index if not exists reminders_due_idx on public.reminders(due_at, completed);
create index if not exists tasks_due_idx on public.tasks(due_at, completed);
create index if not exists notifications_user_idx on public.notifications(user_id, created_at desc);
create index if not exists activity_logs_entity_idx on public.activity_logs(entity_type, entity_id, created_at desc);

insert into public.product_categories(name) values ('Kirana'),('Mid-Day Meal'),('Stationery'),('Printing'),('Government Materials'),('Flags'),('Banners'),('Stickers'),('Files'),('Other') on conflict (name) do nothing;
insert into public.products(name,category_id,unit) select v.name,c.id,v.unit from (values ('Mustard Oil','Kirana','L'),('Soybean','Mid-Day Meal','kg'),('Daal','Mid-Day Meal','kg'),('Turmeric','Kirana','kg'),('Chilli Powder','Kirana','kg'),('Coriander Powder','Kirana','kg'),('Salt','Kirana','kg'),('Flags','Flags','piece'),('Banners','Banners','piece'),('Stickers','Stickers','piece'),('Files','Files','piece')) v(name,cat,unit) join public.product_categories c on c.name=v.cat where not exists(select 1 from public.products p where p.name=v.name);

alter table public.profiles enable row level security;
alter table public.schools enable row level security;
alter table public.school_contacts enable row level security;
alter table public.locations enable row level security;
alter table public.school_visits enable row level security;
alter table public.product_categories enable row level security;
alter table public.products enable row level security;
alter table public.suppliers enable row level security;
alter table public.order_templates enable row level security;
alter table public.order_template_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.deliveries enable row level security;
alter table public.inventory enable row level security;
alter table public.inventory_transactions enable row level security;
alter table public.purchases enable row level security;
alter table public.purchase_items enable row level security;
alter table public.payments enable row level security;
alter table public.reminders enable row level security;
alter table public.tasks enable row level security;
alter table public.notifications enable row level security;
alter table public.attachments enable row level security;
alter table public.activity_logs enable row level security;

do $$ declare t text; begin foreach t in array array['profiles','schools','school_contacts','locations','school_visits','product_categories','products','suppliers','order_templates','order_template_items','orders','order_items','deliveries','inventory','inventory_transactions','purchases','purchase_items','payments','reminders','tasks','notifications','attachments','activity_logs'] loop execute format('drop policy if exists "authenticated access" on public.%I',t); execute format('create policy "authenticated access" on public.%I for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null)',t); end loop; end $$;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['profiles','schools','school_contacts','suppliers','products','order_templates','orders','deliveries','purchases','reminders','tasks'] loop execute format('drop trigger if exists set_updated_at on public.%I',t); execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()',t); end loop; end $$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email)) on conflict(id) do nothing; return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
