'use client';

import { useEffect, useMemo, useState } from 'react';
import AppNav from '@/components/AppNav';
import { createClient } from '@/lib/supabase';
import { Boxes, Download, RefreshCw, Search, TrendingDown, TrendingUp } from 'lucide-react';

type Tx = { id:string; product_id:string; quantity:number|string; transaction_type:string; notes:string|null; created_at:string; products?:{name:string;sku:string|null;unit:string|null}|{name:string;sku:string|null;unit:string|null}[]|null };
const labelDate=(v:string)=>new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});
const productName=(t:Tx)=>Array.isArray(t.products)?t.products[0]?.name||'Unknown product':t.products?.name||'Unknown product';

export default function StockMovementLedger(){
 const db=useMemo(()=>createClient(),[]);
 const [rows,setRows]=useState<Tx[]>([]),[query,setQuery]=useState(''),[type,setType]=useState('ALL'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');const {data,error}=await db.from('inventory_transactions').select('id,product_id,quantity,transaction_type,notes,created_at,products(name,sku,unit)').order('created_at',{ascending:false}).limit(1000);if(error)setError(error.message);setRows((data||[]) as unknown as Tx[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>rows.filter(t=>{const q=query.trim().toLowerCase();const d=t.created_at.slice(0,10);return(!q||[productName(t),Array.isArray(t.products)?t.products[0]?.sku:t.products?.sku,t.transaction_type,t.notes].filter(Boolean).join(' ').toLowerCase().includes(q))&&(type==='ALL'||t.transaction_type===type)&&(!start||d>=start)&&(!end||d<=end)}),[rows,query,type,start,end]);
 const totals=useMemo(()=>({count:visible.length,in:Number(visible.filter(t=>Number(t.quantity)>0).reduce((a,t)=>a+Number(t.quantity),0).toFixed(2)),out:Number(Math.abs(visible.filter(t=>Number(t.quantity)<0).reduce((a,t)=>a+Number(t.quantity),0)).toFixed(2))}),[visible]);
 const exportCsv=()=>{const data=[['Date','Product','SKU','Movement type','Quantity','Unit','Notes'],...visible.map(t=>[labelDate(t.created_at),productName(t),Array.isArray(t.products)?t.products[0]?.sku||'':t.products?.sku||'',t.transaction_type,t.quantity,Array.isArray(t.products)?t.products[0]?.unit||'':t.products?.unit||'',t.notes||''])];const csv=data.map(r=>r.map(v=>{const s=String(v??'');return/[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}).join(',')).join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='guru-kalyanam-stock-movement-ledger.csv';a.click();URL.revokeObjectURL(url)};
 return <div className="min-h-screen flex bg-slate-50"><AppNav/><main className="flex-1 min-w-0 p-4 md:p-8"><div className="max-w-7xl mx-auto space-y-5">
 <header className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-3"><div><p className="text-sm font-semibold text-teal-700 flex items-center gap-2"><Boxes size={16}/> Phase 49 · Inventory</p><h1 className="text-3xl font-bold">Stock Movement Ledger</h1><p className="text-sm text-slate-500 mt-1">A searchable audit trail of stock changes across products.</p></div><div className="flex gap-2"><button onClick={exportCsv} disabled={!visible.length} className="inline-flex items-center justify-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50"><Download size={16}/>Export CSV</button><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50"><RefreshCw size={16} className={loading?'animate-spin':''}/>Refresh</button></div></header>
 {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <section className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div className="card p-4"><p className="text-sm text-slate-500">Movements shown</p><p className="text-2xl font-bold mt-1">{totals.count}</p></div><div className="card p-4"><p className="text-sm text-slate-500 flex items-center gap-2"><TrendingUp size={16} className="text-emerald-600"/>Positive quantity</p><p className="text-2xl font-bold mt-1">{totals.in.toLocaleString('en-IN')}</p></div><div className="card p-4"><p className="text-sm text-slate-500 flex items-center gap-2"><TrendingDown size={16} className="text-rose-600"/>Negative quantity</p><p className="text-2xl font-bold mt-1">{totals.out.toLocaleString('en-IN')}</p></div></section>
 <section className="card p-4 space-y-3"><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-2"><label className="relative sm:col-span-2 xl:col-span-1"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input aria-label="Search stock movements" className="w-full border rounded-xl px-9 py-2.5 text-sm" placeholder="Product, SKU, note…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Movement type" className="border rounded-xl px-3 py-2.5 text-sm bg-white" value={type} onChange={e=>setType(e.target.value)}><option value="ALL">All movement types</option>{['PURCHASE','SALE','ADJUSTMENT','RETURN','DAMAGE','TRANSFER'].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Start date" type="date" className="border rounded-xl px-3 py-2.5 text-sm" value={start} onChange={e=>setStart(e.target.value)}/><input aria-label="End date" type="date" className="border rounded-xl px-3 py-2.5 text-sm" value={end} min={start||undefined} onChange={e=>setEnd(e.target.value)}/></div><div className="flex items-center justify-between text-xs text-slate-500"><span>{loading?'Loading movements…':`Showing ${visible.length} of ${rows.length} recent movements`}</span><button className="underline" onClick={()=>{setQuery('');setType('ALL');setStart('');setEnd('')}}>Clear filters</button></div>
 <div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr className="border-b text-slate-500"><th className="py-3 pr-4 font-semibold">Date</th><th className="py-3 pr-4 font-semibold">Product</th><th className="py-3 pr-4 font-semibold">Type</th><th className="py-3 pr-4 text-right font-semibold">Quantity</th><th className="py-3 font-semibold">Notes</th></tr></thead><tbody>{visible.map(t=><tr key={t.id} className="border-b last:border-0 align-top"><td className="py-3 pr-4 whitespace-nowrap">{labelDate(t.created_at)}</td><td className="py-3 pr-4 min-w-40"><div className="font-semibold">{productName(t)}</div><div className="text-xs text-slate-500">{Array.isArray(t.products)?t.products[0]?.sku:t.products?.sku}</div></td><td className="py-3 pr-4"><span className="inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{t.transaction_type}</span></td><td className={`py-3 pr-4 text-right font-semibold tabular-nums ${Number(t.quantity)<0?'text-rose-600':'text-emerald-700'}`}>{Number(t.quantity)>0?'+':''}{Number(t.quantity).toLocaleString('en-IN')} <span className="text-xs font-normal text-slate-500">{Array.isArray(t.products)?t.products[0]?.unit:t.products?.unit}</span></td><td className="py-3 min-w-40 text-slate-600">{t.notes||'—'}</td></tr>)}{!loading&&visible.length===0&&<tr><td colSpan={5} className="py-12 text-center text-slate-500">No stock movements match these filters.</td></tr>}</tbody></table></div>
 <p className="text-xs text-slate-500">Read-only report · Displays up to the latest 1,000 recorded movements. Use Inventory Control to record stock changes.</p></section>
 </div></main></div>;
}
